source ~/.zsh/antigen.zsh
#source ~/.zsh/powerlvl9k.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/nvm.zsh
source ~/.zsh/p10k.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
#antigen bundle git
#antigen bundle heroku
antigen bundle pip
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the Theme
antigen theme romkatv/powerlevel10k

# Tell Antigen that you're done.
antigen apply
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
