#!/usr/bin/env zsh

function update {
  echo 'start updating ...'

  echo 'updating homebrew'
  brew update
  brew upgrade
  brew reinstall neovim
  brew cleanup

  echo 'updating fish shell'
  fisher
  fish_update_completions

  echo 'checking Apple Updates'
  /usr/sbin/softwareupdate -ia
}
