# HOMEBREW
eval "$(/opt/homebrew/bin/brew shellenv)"

# FNM
if command -v fnm &>/dev/null; then
    eval "$(fnm env --use-on-cd)"
fi

# PYENV
# Disabling for now as I'm testing out uv - https://docs.astral.sh/uv/#learn-more
#if command -v pyenv &>/dev/null; then
#    eval "$(pyenv init -)"
#    eval "$(pyenv virtualenv-init -)"
#fi
