#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export TERM="xterm-256color"
export DOTFILES="$HOME/.dotfiles"
export WORKSPACE="$HOME/workspace"

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# other software
export TMUXP_CONFIGDIR="$XDG_CONFIG_HOME/tmuxp"
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
export GIMP_VERSION="2.10"
export SCREENSHOT="$HOME/Documents/images/screenshots"

# Man pages
export MANPAGER='nvim +Man!'

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

FZF_COLORS="bg+:-1,\
fg:gray,\
fg+:white,\
border:black,\
spinner:0,\
hl:yellow,\
header:blue,\
info:green,\
pointer:red,\
marker:red,\
prompt:gray,\
hl+:red"

export FZF_DEFAULT_OPTS="--height 60% \
--border sharp \
--color='$FZF_COLORS' \
--prompt '∷ ' \
--pointer ▶ \
--marker ⇒"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -n 10'"

# Golang
export GOPATH="$WORKSPACE/go"
export GOBIN="$WORKSPACE/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"

# NPM
export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

# Python
export PYENV_ROOT=$HOME/.pyenv
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS=' -p /usr/bin/python3 '

# JAVA
export JBOSS_HOME="$HOME/tools/jboss"
export TOMCAT_HOME="$HOME/tools/tomcat"
export ACTIVEMQ_HOME="$HOME/tools/activemq"
export JAVA_HOME="/usr/bin/java"

# git
#export GIT_REVIEW_BASE=master # See gitconfig

export PKG_CONFIG_PATH="/opt/homebrew/opt/libpq/lib/pkgconfig"

# OPENSSL
export LIBRARY_PATH=$LIBRARY_PATH:/opt/homebrew/opt/openssl@3/lib/
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/opt/homebrew/opt/openssl@3/include/

# pnpm
export PNPM_HOME="/Users/jzone/.config/local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


# PATH
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

export PATH="$COMPOSER_HOME/vendor/bin:$PATH"                       # COMPOSER
export PATH="$GOBIN:$PATH"                                          # GOBIN
export PATH="$NPM_BIN:$PATH"                                        # NPM
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"	    # GNUBIN
export PATH="$JBOSS_HOME/bin:$PATH"                                 # JBOSS
export PATH="$TOMCAT_HOM/bin:$PATH"                                 # TOMCAT
export PATH="$ACTIVEMQ_HOME/bin:$PATH"                              # ACTIVEMQ
export PATH="$PATH:/Users/jzone/.local/bin"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
