# Evergarden
# Style Hard
[colors]
foreground = "#DDDECF"
background = "#1C2225"
cursor_bg = "#E69875"
cursor_border = "#E69875"
cursor_fg = "#171C1f"
selection_bg = "#3D494D"
selection_fg = "#DDDECF"
compose_cursor = "#DBBC7F"

ansi = [ "#1C2225", "#E67E80", "#B2C98F", "#DBBC7F", "#9BB5CF", "#E3A8D1","#93C9A1", "#DDDECF", ]
brights = [ "#313B40", "#E67E80", "#B2C98F", "#DBBC7F", "#9BB5CF", "#E3A8D1", "#93C9A1", "#94AAA0", ]
