# Evergarden
# Style Medium
[colors]
foreground = "#DDDECF"
background = "#232A2E"
cursor_bg = "#E69875"
cursor_border = "#E69875"
cursor_fg = "#171C1f"
selection_bg = "#3D494D"
selection_fg = "#DDDECF"

compose_cursor = "#DBBC7F"

scrollbar_thumb = "#3D494D"

ansi = [ "#232A2E", "#E67E80", "#B2C98F", "#DBBC7F", "#9BB5CF", "#E3A8D1","#93C9A1", "#DDDECF", ]
brights = [ "#313B40", "#E67E80", "#B2C98F", "#DBBC7F", "#9BB5CF", "#E3A8D1", "#93C9A1", "#94AAA0", ]

